
server.port: 8081
my:
  greeting: Hello world
  list.values: girl,bout,cat
dbValues: "{connectionlink :'http://....',userName:' restypan',password:'123'}"
db:
  host: 127.0.0.1
  port: 1239
management.endpoints.web.exposure.include: "*"
#spring.profiles.active: test
spring.cloud.config.uri: http://localhost:8888
spring:
  application:
    name: spring-boot-config